### PR TITLE
Add talk series; update workshop text to "postponed".

### PR DESCRIPTION
**Pull request by zkbt**
@kevin218 and @hrwakeford , here are my proposed changes to the website for adding the talk series. I'd love if one of you could please take a look before we push this up to site. If you pull down this branch, you should be able to see the whole draft website starting just from opening `index.html` in a browser.

### CODE REVIEW

**Comment by hrwakeford** [comment]
I have had a look at the Workshop page and think those can be pushed. 

The talks page final paragraph needs minor tweaks. I suggest the following:

> This calendar shows the current schedule of upcoming talks, along with the zoom link for the meeting. The meeting will require a password to enter. This password will be sent out to the ERS-transit team and other secure lists. Alternatively, you can get the password by contacting one of us with your name, current research affiliation, and reason for wanting to participate.

**Comment by zkbt** [comment]
Thanks, @hrwakeford !

**Review by kevin218 — APPROVED** [review]
Looks good!

**Comment by nbatalha** [comment]
I cloned the repo after you committed the changes.  When I open the website locally, there's a message above the calendar that says: "Events from one or more calendars could not be shown here because you do not have the permission to view them."  Looks like the calendar doesn't appear at all on the public-facing website.

**Comment by zkbt** [comment]
Thanks for catching that, @nbatalha ! That's the problem with only testing it on my own computer, when I was logged in to my google account. I updated the sharing, so I think it should be OK now.

**Pull request merged**
